// This file is generated by Sapper — do not edit it!
import root from '../routes/_layout.html';
import error from '../routes/_error.html';

const d = decodeURIComponent;

const index = {
	js: () => import('../routes/index.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:index.html__"
};
const about = {
	js: () => import('../routes/about.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:about.html__"
};
const blog = {
	js: () => import('../routes/blog/index.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:blog/index.html__"
};
const blog_$slug = {
	js: () => import('../routes/blog/[slug].html'),
	css: "__SAPPER_CSS_PLACEHOLDER:blog/[slug].html__"
};

export const manifest = {
	ignore: [/^\/blog.json$/, /^\/blog\/([^\/]+?).json$/],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ component: index }
			]
		},

		{
			// about.html
			pattern: /^\/about\/?$/,
			parts: [
				{ component: about }
			]
		},

		{
			// blog/index.html
			pattern: /^\/blog\/?$/,
			parts: [
				null,
				{ component: blog }
			]
		},

		{
			// blog/[slug].html
			pattern: /^\/blog\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ component: blog_$slug, params: match => ({ slug: d(match[1]) }) }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};

import('/Users/208311/Development/SVELTE/sapper/sapper-dev-client.js').then(client => {
	client.connect(10000);
});