// This file is generated by Sapper — do not edit it!
export const timestamp = 1537382818779;

export const files = [
	"favicon.png",
	"global.css",
	"great-success.png",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];
export { files as assets }; // legacy

export const shell = [
	"client/client.70f4572e.js",
	"client/chunk.63008adb.js",
	"client/index.7d57c43d.js",
	"client/about.926a85ba.js",
	"client/index.dd861ecd.js",
	"client/[slug].1c7e9176.js",
	"client/sapper-dev-client.c1ed07a9.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/about\/?$/ },
	{ pattern: /^\/blog\/?$/ },
	{ pattern: /^\/blog\/([^\/]+?)\/?$/ }
];