// This file is generated by Sapper — do not edit it!
import * as route_blog_json from '../routes/blog/index.json.js';
import * as route_blog_$slug_json from '../routes/blog/[slug].json.js';
import index from '../routes/index.html';
import about from '../routes/about.html';
import blog from '../routes/blog/index.html';
import blog_$slug from '../routes/blog/[slug].html';
import root from '../routes/_layout.html';
import error from '../routes/_error.html';

const d = decodeURIComponent;

export const manifest = {
	server_routes: [
		{
			// blog/index.json.js
			pattern: /^\/blog.json$/,
			handlers: route_blog_json,
			params: () => ({})
		},

		{
			// blog/[slug].json.js
			pattern: /^\/blog\/([^\/]+?).json$/,
			handlers: route_blog_$slug_json,
			params: match => ({ slug: d(match[1]) })
		}
	],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ name: "index", file: "index.html", component: index }
			]
		},

		{
			// about.html
			pattern: /^\/about\/?$/,
			parts: [
				{ name: "about", file: "about.html", component: about }
			]
		},

		{
			// blog/index.html
			pattern: /^\/blog\/?$/,
			parts: [
				null,
				{ name: "blog", file: "blog/index.html", component: blog }
			]
		},

		{
			// blog/[slug].html
			pattern: /^\/blog\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ name: "blog_$slug", file: "blog/[slug].html", component: blog_$slug, params: match => ({ slug: d(match[1]) }) }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};