// This file is generated by Sapper — do not edit it!
import _ from '../../routes/index.html';
import _4xx from '../../routes/4xx.html';
import _5xx from '../../routes/5xx.html';
import about from '../../routes/about.html';
import blog from '../../routes/blog/index.html';
import * as api_blog_posts from '../../routes/api/blog-posts.js';
import * as api_blog_$slug$ from '../../routes/api/blog/[slug].js';
import blog_$slug$ from '../../routes/blog/[slug].html';

export const routes = [
	{ id: '_', type: 'page', pattern: /^\/?$/, params: () => ({}), module: _ },
	{ error: '4xx', module: _4xx },
	{ error: '5xx', module: _5xx },
	{ id: 'about', type: 'page', pattern: /^\/about\/?$/, params: () => ({}), module: about },
	{ id: 'blog', type: 'page', pattern: /^\/blog\/?$/, params: () => ({}), module: blog },
	{ id: 'api_blog_posts', type: 'route', pattern: /^\/api\/blog-posts\/?$/, params: () => ({}), module: api_blog_posts },
	{ id: 'api_blog_$slug$', type: 'route', pattern: /^\/api\/blog(?:\/([^\/]+))?\/?$/, params: match => ({ slug: match[1] }), module: api_blog_$slug$ },
	{ id: 'blog_$slug$', type: 'page', pattern: /^\/blog(?:\/([^\/]+))?\/?$/, params: match => ({ slug: match[1] }), module: blog_$slug$ }
];