// This file is generated by Sapper — do not edit it!
export const timestamp = 1518906946124;

export const assets = [
	"favicon.png",
	"global.css",
	"great-success.png",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];

export const shell = [
	"/client/_.0.15d69aa40f5cf2c235b5.js",
	"/client/blog.1.15d69aa40f5cf2c235b5.js",
	"/client/blog_$slug$.2.15d69aa40f5cf2c235b5.js",
	"/client/about.3.15d69aa40f5cf2c235b5.js",
	"/client/_5xx.4.15d69aa40f5cf2c235b5.js",
	"/client/_4xx.5.15d69aa40f5cf2c235b5.js",
	"/client/6.6.15d69aa40f5cf2c235b5.js",
	"/client/main.15d69aa40f5cf2c235b5.js",
	"/client/0.b91f3b4b0888fc3dc282.hot-update.js",
	"/client/b91f3b4b0888fc3dc282.hot-update.json"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/4xx\/?$/ },
	{ pattern: /^\/5xx\/?$/ },
	{ pattern: /^\/about\/?$/ },
	{ pattern: /^\/blog\/?$/ },
	{ pattern: /^\/blog(?:\/([^\/]+))?\/?$/ }
];