// This file is generated by Sapper — do not edit it!
export const timestamp = 1518910653621;

export const assets = [
	"favicon.png",
	"global.css",
	"great-success.png",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];

export const shell = [
	"/client/_.0.6b48eb953c3d3763d72b.js",
	"/client/blog.1.6b48eb953c3d3763d72b.js",
	"/client/blog_$slug$.2.6b48eb953c3d3763d72b.js",
	"/client/about.3.6b48eb953c3d3763d72b.js",
	"/client/_5xx.4.6b48eb953c3d3763d72b.js",
	"/client/_4xx.5.6b48eb953c3d3763d72b.js",
	"/client/6.6.6b48eb953c3d3763d72b.js",
	"/client/main.6b48eb953c3d3763d72b.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/about\/?$/ },
	{ pattern: /^\/blog\/?$/ },
	{ pattern: /^\/blog(?:\/([^\/]+))?\/?$/ }
];